### ISSUE TITLE
Can OLCOrm handle an existed database?

### ISSUE THREAD

**Issue by ngdik** [LakithaRav/OLCOrm#2]
Can OLCOrm open an existed database which created by SQLiteManager, and handle the tables in database by using custom model class?

**Comment by LakithaRav** [comment]
Possible. But OLCOrm rely on Primary-key (INTEGER) field called 'Id'  (or you can set you own key by overriding + (NSString *) primaryKey in your model class) for its CRUD operations. If you database file do have this field, Yes you can use this library .

**Comment by LakithaRav** [comment]
For now you can't. I'm working on some migration code for v1.1.0 so that database version update won't completely create fresh database tables and prevent data lose from old table versions. Soon as that is available you should be able to work with custom database files as well (with some minor changes to that database of course).
v1.1.0 will be coming soon!

**Comment by LakithaRav** [comment]
hey @ngdik **v1.1.0** is available now.
Regarding your question, for this to work following three conditions should be fulfilled;
1. The table names should exactly match the Model names.
2. The column names should exactly match the Model's property names.
3. All tables MUST have Primary-key `Id`(INTEGER) column for OLCOrm to do CRUD operations. In case your's different from `Id` name, override `+ (NSString*) primaryKey` method. 

If all three mentioned conditions are met, initialise the database by calling `OLCOrm *dbH = [OLCOrm databaseName:@"your_exisitng_database.sqlite" version:[NSNumber numberWithInt:2] enableDebug:NO];` with your existing database name. Finally call `[dbH makeTable:[MyModel class]]` on your model(s) to migrate the data. Hopefully it should work.

*please keep a backup of your database first :) cause I haven't tested this scenario my self.
*assume your database file is located in document directory of the app
*for the lib this will be a hack, so can't guarantee it would work as expected.

**Comment by ngdik** [comment]
I got it. Thanks for your answer. 
OLCOrm is a nice ORM library!

**Comment by LakithaRav** [comment]
Thanks!
